services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./config:/root/.minio
    environment:
      MINIO_ROOT_USER: adminoc88
      MINIO_ROOT_PASSWORD: adminoc88Minio@2025
    ports:
      - "9000:9000"   # API Port
      - "9001:9001"   # Web Console
    command: server /data --console-address ":9001"
