version: '3.8'

services:
  redis:
    image: redis:7.2
    container_name: redis-6379
    restart: always
    ports:
      - "6379:6379"
      - "16379:16379"
    volumes:
      - ./data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: >
      redis-server /usr/local/etc/redis/redis.conf
      --cluster-announce-ip 10.170.0.15
      --cluster-announce-port 6379
      --cluster-announce-bus-port 16379

    ulimits:
      nofile:
        soft: 65536
        hard: 65536
